name: BytesDB CI

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  check-license:
    name: Verify Apache License in Go Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check License in Go Files
        run: |
          LICENSE_TEXT="Licensed under the Apache License, Version 2.0"
          MISSING_LICENSE_FILES=()
          
          PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

          for file in $(find "$PROJECT_ROOT" -type f -name '*.go'); do
            if ! grep -q "$LICENSE_TEXT" "$file"; then
              MISSING_LICENSE_FILES+=("$file")
            fi
          done

          if [ ${#MISSING_LICENSE_FILES[@]} -ne 0 ]; then
            echo "The following files are missing the Apache license header:"
            printf '%s\n' "${MISSING_LICENSE_FILES[@]}"
            exit 1
          fi

  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.0
          args: --timeout=5m
          skip-cache: true

  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: |
          go mod download
          go mod tidy
      - name: Test storage package
        run: go test -v ./core/...

  storage-local-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: |
          go mod download
          go mod tidy
      - name: Test file package
        run: go test -v ./storage/file/...

  storage-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: |
          go mod download
          go mod tidy
      - name: Test file package
        run: go test -v ./storage/

  memo-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: |
          go mod download
          go mod tidy
      - name: Test file package
        run: go test -v ./index/...